### ISSUE TITLE
docker-compose up error with 'Couldn't find env file'

### ISSUE THREAD

**Issue by jinhl9** [ayush-lab/Coursera-Clone#2]
Hi, thanks for the project!

Once I cloned the repo and run docker-compose up, I get 'couldn't find env file'.
Is there missing step to start the project?

Thanks a lot

**Comment by ayush-lab** [comment]
Hey @jinhl9! 
You have to create a new .env file in the root directory aka in the same directory as 'docker-compose' file. I didn't add it because of safety reasons
